### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by GhzGarage** [ihyajb/qbcore-code-snippets#1]
Add the next export method:
```
exports['qb-core']:GetCoreObject()
```
Add the new isLoggedIn method:
```
LocalPlayer.state['isLoggedIn']
```

**Comment by ihyajb** [comment]
ah yes I was planning on adding that with 0.0.5, but forgot lol thank you. When I get home later today i'll add those

**Comment by ihyajb** [comment]
Suggestion Added
